### GET all Recipes
GET http://localhost:4000/recipes

### GET Recipe by id
GET http://localhost:4000/recipes/detail/receta-1

### GET Search Recipes by name or ingredients
GET http://localhost:4000/recipes/pasta

### PATCH Add a new rating to a Recipe
PATCH http://localhost:4000/recipes/rating/receta-1
Content-Type: application/json

{
    "rating": 2
}

### GET Recipes by rating asc
GET http://localhost:4000/recipes/rating/desc
Content-Type: application/json
